---
title: "Title for Group"
author: "Ehsan Habibpour, Natalie Short, and Ryan Altman"
date: today
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Load necessary libraries

```{r}
library(tidycensus)
library(dplyr)
library(tidyr)
library(writexl)
library(readr)
library(stringr)
```

```{r}
# get census data
get_census_year_data <- function(year_tg, price_index, nt = 2) {
  # Define variables
  variables <- c(
    houseowners_total = "B25087_001E", #Housing units
    houseowners_with_mortgage = "B25087_002E", #Housing units with a mortgage
    houseowners_without_mortgage = "B25087_020E", #Housing units without a mortgage
    house_value_median = "B25077_001E", #Median Value
    owner_cost_median = "B25088_001E", #Median selected monthly owner costs
    owner_cost_median_with_mortgage = "B25088_002E", #same with mortgage
    owner_cost_median_without_mortgage = "B25088_003E", #same without mortgage
    owner_cost_to_income_median = "B25092_001E", #sama as a percentage of yearly income
    owner_cost_to_income_median_with_mortgage = "B25092_002E", #same with mortgage
    owner_cost_to_income_median_without_mortgage = "B25092_003E" #same without mortgage
  )

  # Get census data
  census_data <- get_acs(
    geography = "county",
    variables = variables,
    year = year_tg,
    survey = "acs5",
    output = "wide"
  )

  # Process data
  census_data <- census_data %>%
    select(GEOID, NAME, all_of(names(variables))) %>%
    mutate(
      state_fips = as.numeric(substr(GEOID, 1, 2)),    # Extract first 2 digits for state FIPS
      county_fips = as.numeric(substr(GEOID, 3, 5)),   # Extract last 3 digits for county FIPS
      state = sub(".*,\\s*", "", NAME),
      county = sub(",\\s*[^,]*$", "", NAME)
    ) %>%
    mutate(
      county = str_remove(county, " County$"),
      county = str_remove(county, " Census Area$"),
      county = str_remove(county, " Municipio$"),
      county = str_remove(county, " Parish$"),
      county = str_remove(county, " Borough$"),
      county = str_remove(county, " Planning Region$"),
      county = str_remove(county, " city$")
    ) %>%
    mutate(
      house_value_median = house_value_median/price_index,
      owner_cost_median = owner_cost_median * 12/price_index,
      owner_cost_median_with_mortgage = owner_cost_median_with_mortgage * 12/price_index,
      owner_cost_median_without_mortgage = owner_cost_median_without_mortgage * 12/price_index,
      year = year_tg
    ) %>%
    select(
      GEOID, state_fips, county_fips, state, county, year, houseowners_total,
      houseowners_with_mortgage, houseowners_without_mortgage, house_value_median,
      owner_cost_median,
      owner_cost_median_with_mortgage, owner_cost_median_without_mortgage,
      owner_cost_to_income_median, owner_cost_to_income_median_with_mortgage,
      owner_cost_to_income_median_without_mortgage
    )
  
  return(census_data)
}

# Get data for each year
census_data_2023 <- get_census_year_data(2023, 1) 
census_data_2018 <- get_census_year_data(2018, 0.824)
census_data_2013 <- get_census_year_data(2013, 0.765)

# Combine all years into one dataset
census_data_total <- bind_rows(
  census_data_2023,
  census_data_2018,
  census_data_2013
)

# Sort the final dataset
census_data_total <- census_data_total %>%
  arrange(state, county, year)
```
